name: Main
on: [push]
env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: terraform fmt -recursive -check
      - name: Initialize
        run: terraform init
      - name: Apply
        run: terraform apply
      - name: Idempotency Check
        run: terraform plan -detailed-exitcode
